#!/usr/bin/env python3
"""Convert all Markdown reports to styled HTML reports.
Usage: python3 generate_html.py [base_dir]
  - Without argument: uses default Butian SRC path
  - With argument: uses specified directory (for ZC projects)
"""
import os
import sys
import markdown
import re
from pathlib import Path

DEFAULT_BASE_DIR = "/home/my/SRC/BSRC"
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
body {{ font-family: -apple-system, "Microsoft YaHei", "PingFang SC", sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
.report-container {{ background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }}
h1 {{ color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px; }}
h2 {{ color: #1976d2; margin-top: 25px; border-left: 4px solid #1976d2; padding-left: 10px; }}
h3 {{ color: #333; margin-top: 20px; }}
table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f0f0f0; font-weight: 600; }}
tr:nth-child(even) {{ background: #fafafa; }}
code {{ background: #f0f0f0; padding: 2px 5px; border-radius: 3px; font-family: "Consolas", "Courier New", monospace; font-size: 0.9em; }}
pre {{ background: #1e1e1e; color: #d4d4d4; padding: 15px; border-radius: 5px; overflow-x: auto; font-size: 0.85em; line-height: 1.4; }}
pre code {{ background: none; padding: 0; color: inherit; }}
blockquote {{ border-left: 4px solid #ff9800; background: #fff8e1; padding: 10px 15px; margin: 15px 0; }}
hr {{ border: none; border-top: 1px solid #ddd; margin: 20px 0; }}
.severity-critical {{ display: inline-block; background: #b71c1c; color: #fff; padding: 3px 10px; border-radius: 3px; font-weight: bold; }}
.severity-high {{ display: inline-block; background: #d32f2f; color: #fff; padding: 3px 10px; border-radius: 3px; font-weight: bold; }}
.severity-medium {{ display: inline-block; background: #f57c00; color: #fff; padding: 3px 10px; border-radius: 3px; font-weight: bold; }}
.severity-low {{ display: inline-block; background: #fbc02d; color: #333; padding: 3px 10px; border-radius: 3px; font-weight: bold; }}
.http-request {{ background: #e3f2fd; border-left: 4px solid #1565c0; padding: 10px; margin: 10px 0; font-family: monospace; white-space: pre-wrap; }}
.http-response {{ background: #e8f5e9; border-left: 4px solid #2e7d32; padding: 10px; margin: 10px 0; font-family: monospace; white-space: pre-wrap; }}
.footer {{ text-align: center; color: #999; margin-top: 30px; font-size: 0.9em; border-top: 1px solid #eee; padding-top: 15px; }}
</style>
</head>
<body>
<div class="report-container">
{content}
<div class="footer">Generated by Butian SRC Report Generator | 2026-05-31</div>
</div>
</body>
</html>"""


def convert_md_to_html(md_path, html_path):
    """Convert a single MD file to styled HTML."""
    with open(md_path, "r", encoding="utf-8") as f:
        md_text = f.read()

    # Get title from first h1
    title_match = re.search(r'^#\s+(.+)$', md_text, re.MULTILINE)
    title = title_match.group(1) if title_match else os.path.basename(md_path)

    # Convert markdown to HTML
    html_body = markdown.markdown(
        md_text,
        extensions=['extra', 'codehilite', 'tables', 'sane_lists']
    )

    # Wrap in template
    full_html = HTML_TEMPLATE.format(title=title, content=html_body)

    os.makedirs(os.path.dirname(html_path), exist_ok=True)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(full_html)

    return html_path


def process_directory(company_dir):
    """Process reports/ and submittable_reports/ directories for a company."""
    name = os.path.basename(company_dir)
    results = {"name": name, "md_count": 0, "html_count": 0}

    for subdir in ["reports", "submittable_reports"]:
        src_dir = os.path.join(company_dir, subdir)
        if not os.path.isdir(src_dir):
            continue
        reports_dir = os.path.join(src_dir, "reports_html")
        for fname in os.listdir(src_dir):
            if not fname.endswith(".md") or fname == "README.md" or fname == "evidence.md":
                continue
            md_path = os.path.join(src_dir, fname)
            html_name = fname.replace(".md", ".html")
            html_path = os.path.join(reports_dir, html_name)
            try:
                convert_md_to_html(md_path, html_path)
                results["html_count"] += 1
            except Exception as e:
                print(f"  ERROR: {md_path} -> {e}")
        results["md_count"] += len([f for f in os.listdir(src_dir) if f.endswith('.md') and f not in ('README.md', 'evidence.md')])

    return results


def main():
    # Accept optional base directory argument
    if len(sys.argv) > 1:
        base_dir = sys.argv[1]
    else:
        base_dir = DEFAULT_BASE_DIR

    if not os.path.isdir(base_dir):
        print(f"ERROR: Directory not found: {base_dir}")
        sys.exit(1)

    print(f"Processing reports under: {base_dir}")
    total_html = 0
    total_md = 0
    for entry in sorted(os.listdir(base_dir)):
        company_dir = os.path.join(base_dir, entry)
        if not os.path.isdir(company_dir):
            continue
        has_reports = False
        for subdir in ["reports", "submittable_reports"]:
            check_dir = os.path.join(company_dir, subdir)
            if os.path.isdir(check_dir) and any(f.endswith(".md") and f not in ("README.md","evidence.md") for f in os.listdir(check_dir)):
                has_reports = True
                break
        if not has_reports:
            continue

        print(f"Processing: {entry}")
        r = process_directory(company_dir)
        print(f"  MD: {r['md_count']}, HTML generated: {r['html_count']}")
        total_md += r['md_count']
        total_html += r['html_count']

    print(f"\nTotal: {total_md} MD files -> {total_html} HTML files generated")


if __name__ == "__main__":
    main()
